export default {
  DISCONNECT: 'disconnect',
  CONNECT: 'connect',

  //Chat events
  CHAT_MESSAGE_RECEIVED: 'CHAT_MESSAGE_RECEIVED',

  //Lobby events
  PLAYERS_LEFT: 'PLAYERS_LEFT',
  PLAYERS_JOINED: 'PLAYERS_JOINED',
  PLAYER_JOINED_GAME: 'PLAYER_JOINED_GAME',
  PLAYER_LEFT_GAME: 'PLAYER_LEFT_GAME',
  ADD_GAMES: 'ADD_GAMES',
  UPDATE_GAME: 'UPDATE_GAME'
};
