import React from 'react';
import text from '@styles/text.css';
import {Link} from 'react-router-dom';

export default props => (
  <section>
    <div className={`${text.title} ${text.center}`}>Node Shooter</div>
    <br/>
    <div className={`${text.bold} ${text.center}`}>
      Node Shooter has been integrated into the <Link to="/projects/NodeSocial">Social App</Link> project. This page just provides a description of it.
    </div>
    <hr/>
    <p>{"This mini-project was an idea I had to create a 'loopless' game engine for the server side for  multiplayer online games. The only third party library used is Socket.IO to aid with client-server communication. The rest is raw JavaScript. Most game engines for MMO's use game loops which is often a waste of resources, especially considering there are no graphics to update on the server. So instead of calculating movement and collisions through the traditional method (checking if objects 'cross over' each other 20-30 times per second), it uses an events-based system; objects are updated, and collisions are calculated (via mathematical interpolation) only when events are generated by users or generated from collisions."}</p>

    <p>{"The collision engine was the main hurdle. First it calculates if a collision will occur in the first place, and if so, how long from now, but only provided the colliding objects remain on course. If any of the objects change size or direction then the 'not yet activated' collision event is cancelled. In theory, this should substantially reduce server load due to only needing to update objects, calculate collisions and send messages to each player as and when events occur, rather than 20-30 times per second as is usually the case with game loops."}</p>

    <p>{"It works best with slower paced games with not too many players/NPCs where events will (on avg.) occur less than 20 times per second. If there are more than ~25 events occuring per second then it may start to perform worse than the traditional method. For now, I have only made it to work between circular objects. Objects of other shapes (maybe except ellipses) will likely require a completely different algorithm. Modifying the current algorithm to work with ellipses and an algorithm to work with any polygon (with all angles &lt;180 degrees) should be able to cover all cases."}</p>

  </section>
);
