export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const LOCAL_LOGIN_SUCCESS = 'LOCAL_LOGIN_SUCCESS';
export const LOCAL_LOGIN_ERROR = 'LOCAL_LOGIN_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_ERROR = 'PROFILE_UPDATE_ERROR';
export const LINK_SUCCESS = 'LINK_SUCCESS';
export const LINK_ERROR = 'LINK_ERROR';
export const UNLINK_SUCCESS = 'UNLINK_SUCCESS';
export const UNLINK_ERROR = 'UNLINK_ERROR';
export const ENTER_PROFILE_EDIT_MODE = 'ENTER_PROFILE_EDIT_MODE';
export const EXIT_PROFILE_EDIT_MODE = 'EXIT_PROFILE_EDIT_MODE';
export const LOGIN_DIALOG_CLOSED = 'LOGIN_DIALOG_CLOSED';

//Until reimplemented templating on backend...
export const INITIATE_USER_SUCCESS = 'INITIATE_USER_SUCCESS';
