//Chat actions
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SET_PLAYERS = 'SET_PLAYERS';
export const ADD_PLAYERS = 'ADD_PLAYERS';
export const REMOVE_PLAYERS = 'REMOVE_PLAYERS';
export const SET_PLAYERS_OFFLINE = 'SET_PLAYERS_OFFLINE';

//Lobby actions
export const CREATE_GAME = 'CREATE_GAME';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_ERROR = 'CREATE_GAME_ERROR';
export const JOIN_GAME_SUCCESS = 'JOIN_GAME_SUCCESS';
export const JOIN_GAME_ERROR = 'JOIN_GAME_ERROR';
